---
ID: "65277016-61d8-48d5-83e3-71d7cafebfca"
Parent: "b9bee1fa-9d3f-4d29-87f2-436a73d458a2"
Template: "b9bee1fa-9d3f-4d29-87f2-436a73d458a2"
Path: "/sitecore/templates/Project/fmc-custom-demo/Components/Content/DualPromoBlock/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260512T213201Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "611b797c-b9e0-4c45-801c-1919560ca80a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260512T213201Z
