---
ID: "c7531105-9bb7-48be-b97d-8f6235c99ee6"
Parent: "0a304dbe-c9c6-4106-b3cf-c6704931ff6a"
Template: "0a304dbe-c9c6-4106-b3cf-c6704931ff6a"
Path: "/sitecore/templates/Project/fmc-custom-demo/Folders/DualPromoBanner Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{23E45CBB-6CE4-44E8-B7E8-49C5CCD5CF77}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "12bd1d0b-6c65-47fe-8122-8409ef3ce352"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260512T213224Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "445d67b0-7f55-4382-98f4-4a9d87a36cde"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\federico.mujica@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260512T213229Z
